-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/restart",
    [2] = "run:gvim",
    [3] = "run:google-chrome",
    [4] = "menu.mainmenu:session/exit",
    [5] = "workspacelayout:",
    [6] = "workspacename:",
    [7] = "workspacename:1",
    [8] = "menu.mainmenu:session/re",
    [9] = "filename:/home/nik/raket/supertalk.c",
    [10] = "filename:/home/nik/",
    [11] = "run:dmenu_run",
    [12] = "workspacename:WGroupWS<1>",
    [13] = "yesno:",
    [14] = "windowname:nik@dev: ~",
    [15] = "windowname:",
    [16] = "windowname:Notion keyboard reference - Google Chrome",
    [17] = "workspacename:Ny",
    [18] = "workspacename:WGroupWS<3>",
}

